version: '3'
services:
  web:
    build: .
    image: zicodev01/wolf:latest
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web