name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via scp
      run: |
        scp -r ./* user@server_ip:/path/to/destination_directory

    - name: SSH and deploy
      run: |
        ssh user@server_ip <<EOF
          cd /path/to/destination_directory
          sudo docker-compose down
          sudo docker-compose up --build -d
        EOF
